blank_issues_enabled: false
contact_links:
  - name: GitHub Discussions
    url: https://github.com/guitarbeat/scanimage-zcontrol/discussions
    about: Ask questions and discuss ideas with the community
  - name: Documentation
    url: https://github.com/guitarbeat/scanimage-zcontrol/blob/main/README.md
    about: Check the documentation for answers to common questions