classdef AppConfig < handle
    % AppConfig - Centralized configuration for the application
    %
    % This class provides a single source of truth for application configuration,
    % including version information, default parameters, and UI settings.
    
    properties (Constant)
        % Application info
        VERSION = '1.1.0'
        BUILD_DATE = 'May 2025'
        
        % Default parameters
        DEFAULT_STEP_SIZE = 1
        DEFAULT_INITIAL_STEP_SIZE = 20
        DEFAULT_SCAN_PAUSE_TIME = 0.5
        DEFAULT_RANGE_LOW = -25
        DEFAULT_RANGE_HIGH = 25
        DEFAULT_SMOOTHING_WINDOW = 3
        DEFAULT_AUTO_UPDATE_FREQUENCY = 1
        DEFAULT_MAX_POINTS = 1000
        DEFAULT_METRIC = 7
        DEFAULT_AVERAGE_TIME_WINDOW = 5
        DEFAULT_MONITORING_TIMER_PERIOD = 0.25
        
        % UI settings
        UI_COLORS = struct(...
            'Primary', [0.2 0.4 0.8], ...
            'Secondary', [0.6 0.6 0.7], ...
            'Success', [0.2 0.7 0.3], ...
            'Warning', [0.9 0.6 0.1], ...
            'Danger', [0.8 0.2 0.2], ...
            'Background', [0.96 0.96 0.98], ...
            'Surface', [1 1 1], ...
            'Border', [0.8 0.8 0.8], ...
            'Text', [0.2 0.2 0.2], ...
            'TextLight', [0.5 0.5 0.5], ...
            'ActionButton', [0.85 0.95 0.95], ...
            'ScanButton', [0.7 0.85 1.0], ...
            'EmergencyButton', [1.0 0.7 0.7], ...
            'BestFocusButton', [1.0 0.85 0.85] ...
        )
        
        UI_FONTS = struct(...
            'DefaultSize', 11, ...
            'SmallSize', 9, ...
            'LargeSize', 13, ...
            'TitleSize', 15 ...
        )
        
        UI_SPACING = struct(...
            'Small', 5, ...
            'Medium', 8, ...
            'Large', 10, ...
            'XLarge', 15 ...
        )
    end
    
    methods (Static)
        function params = getDefaultParameters()
            % Returns default parameters as a struct
            params = struct(...
                'stepSize', core.AppConfig.DEFAULT_STEP_SIZE, ...
                'initialStepSize', core.AppConfig.DEFAULT_INITIAL_STEP_SIZE, ...
                'scanPauseTime', core.AppConfig.DEFAULT_SCAN_PAUSE_TIME, ...
                'rangeLow', core.AppConfig.DEFAULT_RANGE_LOW, ...
                'rangeHigh', core.AppConfig.DEFAULT_RANGE_HIGH, ...
                'smoothingWindow', core.AppConfig.DEFAULT_SMOOTHING_WINDOW, ...
                'autoUpdateFrequency', core.AppConfig.DEFAULT_AUTO_UPDATE_FREQUENCY, ...
                'maxPoints', core.AppConfig.DEFAULT_MAX_POINTS, ...
                'defaultMetric', core.AppConfig.DEFAULT_METRIC, ...
                'averageTimeWindow', core.AppConfig.DEFAULT_AVERAGE_TIME_WINDOW, ...
                'monitoringTimerPeriod', core.AppConfig.DEFAULT_MONITORING_TIMER_PERIOD ...
            );
        end
        
        function isCompatible = checkCompatibility(feature)
            % Checks if the current MATLAB version is compatible with a feature
            % Uses CoreUtils.hasAppDesignerFeature to check
            isCompatible = core.CoreUtils.hasAppDesignerFeature(feature);
        end
        
        function showVersion()
            % Display version information
            fprintf('FocalSweep version %s (%s)\n', ...
                core.AppConfig.VERSION, core.AppConfig.BUILD_DATE);
        end
    end
end 